### ISSUE TITLE
Extension not working on Arc browser

### ISSUE THREAD

**Issue by ShaiAvr** [jmerle/cg-local-ext#33]
I am using the [Arc browser](https://arc.net/) and from some reason, the CG local extension isn't working for me. Arc is chromium based, so I installed the Chrome extension. I installed and ran the application:

![Screenshot 2024-10-05 111512](https://github.com/user-attachments/assets/c425d994-5028-4103-aa69-3bfaab1fe27c)
According to your [post](https://www.codingame.com/forum/t/cg-local/10359), I should find a setting to use an external editor in a puzzle, but I don't:

![Screenshot 2024-10-05 111758](https://github.com/user-attachments/assets/ea72046d-a44f-4d40-a56c-b3b6c66d1063)
I also tried to click the extension icon on the top right corner, but it doesn't do anything.

On Firefox there is also no new setting in a puzzle:

![Screenshot 2024-10-05 112025](https://github.com/user-attachments/assets/6ed6fe86-d5df-4176-925d-b72682f70d8e)
However, this time when I click on the extension icon, it does connect to the app and allows me to proceed:

![Screenshot 2024-10-05 112225](https://github.com/user-attachments/assets/17d3734a-ff52-41a6-af20-f15c741cc2c3)
It looks like the instructions on the forum are wrong and you need to click the extension icon instead of toggling a setting on the settings menu of a puzzle.

Even if that is the case, it doesn't work on the Arc browser. The extension icon doesn't do anything and I am unable to use an external editor with this browser.

**Comment by jmerle** [comment]
I only provide support for CG Local on Chrome and Firefox. For other browsers, like Arc, I cannot guarantee compatibility or provide support for them.
